/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppCallsRouteImport } from './routes/_app/calls'
import { Route as AppChatRouteImport } from './routes/_app/chat'
import { Route as AppErpRouteImport } from './routes/_app/erp'
import { Route as AppFilesRouteImport } from './routes/_app/files'
import { Route as AppHiveRouteImport } from './routes/_app/hive'
import { Route as AppMailRouteImport } from './routes/_app/mail'
import { Route as AppMeetingsRouteImport } from './routes/_app/meetings'
import { Route as AppTasksRouteImport } from './routes/_app/tasks'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as AppErpIndexRouteImport } from './routes/_app/erp.index'
import { Route as AppErpDoctypeRouteImport } from './routes/_app/erp.$doctype'
import { Route as AppMeetingsIndexRouteImport } from './routes/_app/meetings.index'
import { Route as AppMeetingsIdRouteImport } from './routes/_app/meetings.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppErpDoctypeIndexRouteImport } from './routes/_app/erp.$doctype.index'
import { Route as AppErpDoctypeNameRouteImport } from './routes/_app/erp.$doctype.$name'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCallsRoute = AppCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppErpRoute = AppErpRouteImport.update({
  id: '/erp',
  path: '/erp',
  getParentRoute: () => AppRoute,
} as any)
const AppFilesRoute = AppFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AppRoute,
} as any)
const AppHiveRoute = AppHiveRouteImport.update({
  id: '/hive',
  path: '/hive',
  getParentRoute: () => AppRoute,
} as any)
const AppMailRoute = AppMailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingsRoute = AppMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AppErpIndexRoute = AppErpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppErpRoute,
} as any)
const AppErpDoctypeRoute = AppErpDoctypeRouteImport.update({
  id: '/$doctype',
  path: '/$doctype',
  getParentRoute: () => AppErpRoute,
} as any)
const AppMeetingsIndexRoute = AppMeetingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMeetingsRoute,
} as any)
const AppMeetingsIdRoute = AppMeetingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppMeetingsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppErpDoctypeIndexRoute = AppErpDoctypeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppErpDoctypeRoute,
} as any)
const AppErpDoctypeNameRoute = AppErpDoctypeNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => AppErpDoctypeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/calls': typeof AppCallsRoute
  '/chat': typeof AppChatRoute
  '/erp': typeof AppErpRouteWithChildren
  '/files': typeof AppFilesRoute
  '/hive': typeof AppHiveRoute
  '/mail': typeof AppMailRoute
  '/meetings': typeof AppMeetingsRouteWithChildren
  '/tasks': typeof AppTasksRoute
  '/api/mcp': typeof ApiMcpRoute
  '/erp/$doctype': typeof AppErpDoctypeRouteWithChildren
  '/meetings/$id': typeof AppMeetingsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/erp/': typeof AppErpIndexRoute
  '/meetings/': typeof AppMeetingsIndexRoute
  '/erp/$doctype/$name': typeof AppErpDoctypeNameRoute
  '/erp/$doctype/': typeof AppErpDoctypeIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/calls': typeof AppCallsRoute
  '/chat': typeof AppChatRoute
  '/files': typeof AppFilesRoute
  '/hive': typeof AppHiveRoute
  '/mail': typeof AppMailRoute
  '/tasks': typeof AppTasksRoute
  '/api/mcp': typeof ApiMcpRoute
  '/': typeof AppIndexRoute
  '/meetings/$id': typeof AppMeetingsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/erp': typeof AppErpIndexRoute
  '/meetings': typeof AppMeetingsIndexRoute
  '/erp/$doctype/$name': typeof AppErpDoctypeNameRoute
  '/erp/$doctype': typeof AppErpDoctypeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/calls': typeof AppCallsRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/erp': typeof AppErpRouteWithChildren
  '/_app/files': typeof AppFilesRoute
  '/_app/hive': typeof AppHiveRoute
  '/_app/mail': typeof AppMailRoute
  '/_app/meetings': typeof AppMeetingsRouteWithChildren
  '/_app/tasks': typeof AppTasksRoute
  '/api/mcp': typeof ApiMcpRoute
  '/_app/': typeof AppIndexRoute
  '/_app/erp/$doctype': typeof AppErpDoctypeRouteWithChildren
  '/_app/meetings/$id': typeof AppMeetingsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/erp/': typeof AppErpIndexRoute
  '/_app/meetings/': typeof AppMeetingsIndexRoute
  '/_app/erp/$doctype/$name': typeof AppErpDoctypeNameRoute
  '/_app/erp/$doctype/': typeof AppErpDoctypeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/calls'
    | '/chat'
    | '/erp'
    | '/files'
    | '/hive'
    | '/mail'
    | '/meetings'
    | '/tasks'
    | '/api/mcp'
    | '/erp/$doctype'
    | '/meetings/$id'
    | '/api/auth/$'
    | '/erp/'
    | '/meetings/'
    | '/erp/$doctype/$name'
    | '/erp/$doctype/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/calls'
    | '/chat'
    | '/files'
    | '/hive'
    | '/mail'
    | '/tasks'
    | '/api/mcp'
    | '/'
    | '/meetings/$id'
    | '/api/auth/$'
    | '/erp'
    | '/meetings'
    | '/erp/$doctype/$name'
    | '/erp/$doctype'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/calls'
    | '/_app/chat'
    | '/_app/erp'
    | '/_app/files'
    | '/_app/hive'
    | '/_app/mail'
    | '/_app/meetings'
    | '/_app/tasks'
    | '/api/mcp'
    | '/_app/'
    | '/_app/erp/$doctype'
    | '/_app/meetings/$id'
    | '/api/auth/$'
    | '/_app/erp/'
    | '/_app/meetings/'
    | '/_app/erp/$doctype/$name'
    | '/_app/erp/$doctype/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calls': {
      id: '/_app/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof AppCallsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/erp': {
      id: '/_app/erp'
      path: '/erp'
      fullPath: '/erp'
      preLoaderRoute: typeof AppErpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/files': {
      id: '/_app/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof AppFilesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hive': {
      id: '/_app/hive'
      path: '/hive'
      fullPath: '/hive'
      preLoaderRoute: typeof AppHiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mail': {
      id: '/_app/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof AppMailRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meetings': {
      id: '/_app/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof AppMeetingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/erp/': {
      id: '/_app/erp/'
      path: '/'
      fullPath: '/erp/'
      preLoaderRoute: typeof AppErpIndexRouteImport
      parentRoute: typeof AppErpRoute
    }
    '/_app/erp/$doctype': {
      id: '/_app/erp/$doctype'
      path: '/$doctype'
      fullPath: '/erp/$doctype'
      preLoaderRoute: typeof AppErpDoctypeRouteImport
      parentRoute: typeof AppErpRoute
    }
    '/_app/meetings/': {
      id: '/_app/meetings/'
      path: '/'
      fullPath: '/meetings/'
      preLoaderRoute: typeof AppMeetingsIndexRouteImport
      parentRoute: typeof AppMeetingsRoute
    }
    '/_app/meetings/$id': {
      id: '/_app/meetings/$id'
      path: '/$id'
      fullPath: '/meetings/$id'
      preLoaderRoute: typeof AppMeetingsIdRouteImport
      parentRoute: typeof AppMeetingsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/erp/$doctype/': {
      id: '/_app/erp/$doctype/'
      path: '/'
      fullPath: '/erp/$doctype/'
      preLoaderRoute: typeof AppErpDoctypeIndexRouteImport
      parentRoute: typeof AppErpDoctypeRoute
    }
    '/_app/erp/$doctype/$name': {
      id: '/_app/erp/$doctype/$name'
      path: '/$name'
      fullPath: '/erp/$doctype/$name'
      preLoaderRoute: typeof AppErpDoctypeNameRouteImport
      parentRoute: typeof AppErpDoctypeRoute
    }
  }
}

interface AppErpDoctypeRouteChildren {
  AppErpDoctypeNameRoute: typeof AppErpDoctypeNameRoute
  AppErpDoctypeIndexRoute: typeof AppErpDoctypeIndexRoute
}

const AppErpDoctypeRouteChildren: AppErpDoctypeRouteChildren = {
  AppErpDoctypeNameRoute: AppErpDoctypeNameRoute,
  AppErpDoctypeIndexRoute: AppErpDoctypeIndexRoute,
}

const AppErpDoctypeRouteWithChildren = AppErpDoctypeRoute._addFileChildren(
  AppErpDoctypeRouteChildren,
)

interface AppErpRouteChildren {
  AppErpDoctypeRoute: typeof AppErpDoctypeRouteWithChildren
  AppErpIndexRoute: typeof AppErpIndexRoute
}

const AppErpRouteChildren: AppErpRouteChildren = {
  AppErpDoctypeRoute: AppErpDoctypeRouteWithChildren,
  AppErpIndexRoute: AppErpIndexRoute,
}

const AppErpRouteWithChildren =
  AppErpRoute._addFileChildren(AppErpRouteChildren)

interface AppMeetingsRouteChildren {
  AppMeetingsIdRoute: typeof AppMeetingsIdRoute
  AppMeetingsIndexRoute: typeof AppMeetingsIndexRoute
}

const AppMeetingsRouteChildren: AppMeetingsRouteChildren = {
  AppMeetingsIdRoute: AppMeetingsIdRoute,
  AppMeetingsIndexRoute: AppMeetingsIndexRoute,
}

const AppMeetingsRouteWithChildren = AppMeetingsRoute._addFileChildren(
  AppMeetingsRouteChildren,
)

interface AppRouteChildren {
  AppCallsRoute: typeof AppCallsRoute
  AppChatRoute: typeof AppChatRoute
  AppErpRoute: typeof AppErpRouteWithChildren
  AppFilesRoute: typeof AppFilesRoute
  AppHiveRoute: typeof AppHiveRoute
  AppMailRoute: typeof AppMailRoute
  AppMeetingsRoute: typeof AppMeetingsRouteWithChildren
  AppTasksRoute: typeof AppTasksRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCallsRoute: AppCallsRoute,
  AppChatRoute: AppChatRoute,
  AppErpRoute: AppErpRouteWithChildren,
  AppFilesRoute: AppFilesRoute,
  AppHiveRoute: AppHiveRoute,
  AppMailRoute: AppMailRoute,
  AppMeetingsRoute: AppMeetingsRouteWithChildren,
  AppTasksRoute: AppTasksRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
